[project]
name = "binance-mcp"
version = "0.1.0"
description = "This is repo for binance mcp"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.11"
dependencies = [
    "fastmcp>=2.12.4",
    "httpx>=0.27.0",
    "python-dotenv>=1.0.0",
]
